- name: finding
  color: "d73a4a"
  description: finding

- name: cap
  color: "016cb8"
  description: CAP

- name: tech-debt
  color: "fbca04"
  description: Technical debt

- name: ticked
  color: "5d01b8"
  description: Ticked

- name: checkout-development
  color: "0112b8"
  description: Checkout - Development

- name: frontend
  color: "1d76db"
  description: Frontend work

- name: backend
  color: "5319e7"
  description: Backend work
