name: Finding
description: Finding in existing code.
title: "[Finding]: "
labels: ["finding", "checkout-development"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
        ## Summary
        
        <!-- Describe the change or task -->
        
        ## Reproduction Steps (Optional)
        
        - [ ]  <!-- Step 1 -->
        
        ## Acceptance Criteria
        
        - [ ]  <!-- Criterion 1 -->
    validations:
      required: true